---
- name: Install logwatch
  ansible.builtin.apt:
    name:
      - nullmailer
      - logwatch
      - libdate-manip-perl
    state: present
    install_recommends: false

- name: Configure logwatch
  ansible.builtin.template:
    src: "logwatch.conf.j2"
    dest: "/etc/logwatch/conf/logwatch.conf"
    mode: "0644"

- name: Remove logwatch cron
  ansible.builtin.file:
    path: /etc/cron.daily/00logwatch
    state: absent

- name: Copy logwatch service files
  ansible.builtin.copy:
    src: logwatch.service
    dest: /etc/systemd/system/logwatch.service
    owner: root
    group: root
    mode: '0644'

- name: Copy logwatch timer files
  ansible.builtin.template:
    src: "logwatch.timer.j2"
    dest: "/etc/systemd/system/logwatch.timer"
    owner: root
    group: root
    mode: "0644"

- name: Enable a timer unit for logwatch
  ansible.builtin.systemd_service:
    name: logwatch.timer
    state: started
    enabled: true
