name: deployment

on:
  # schedule:
  #   - cron: "0 20 * * 0"   # <=== Change this value
  workflow_dispatch:

jobs:
  build:
    name: Ansible Playbook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: playbook.yml
          # Optional, directory where playbooks live
          directory: ./
          # Optional, ansible configuration file content (ansible.cfg)
          configuration: |
            [defaults]
            callbacks_enabled = ansible.posix.profile_tasks, ansible.posix.timer
            stdout_callback = yaml
            nocows = false
          # Optional, SSH private key
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Optional, literal inventory file contents
          inventory: ${{ secrets.HOSTS_YML }}
          # Optional, galaxy requirements filepath
          requirements: requirements.yml
